<?php

if (!empty($_GET['debug'])) {
	ini_set('display_errors', 1);
	error_reporting(E_ALL);
}

define('WEBROOT', dirname(__FILE__));
define('REQUEST_PATH', rtrim( isset($_SERVER['DOCUMENT_URI']) ? $_SERVER['DOCUMENT_URI'] : (isset($_SERVER['REDIRECT_URL']) ? $_SERVER['REDIRECT_URL'] : ''), '/' ));


// handle trailing slashes
if (is_file($f=WEBROOT.REQUEST_PATH)) {
	header('content-type: text/html; charset=utf-8');
	header('x-msg-app: trailing-slash');
	include $f;
	exit;
}

// handle index.html files with querystrings
// e.g. request /taste/ and we only have /taste/index.html?m=true
if (is_dir($dir=WEBROOT.REQUEST_PATH) && !is_file($index=WEBROOT.REQUEST_PATH.'/index.html')) {
	$files = scandir($dir);
	foreach ($files as $file) {
		if (strpos($file,'index.html') === 0) {
			if (copy($dir.'/'.$file, $index)) { // fix if possible
				header('x-msg-app-c: convoluted index.html (copied)');
				break;
			}
			header('content-type: text/html; charset=utf-8');
			header('x-msg-app: convoluted index.html fallback (unable to copy)');
			include $dir.'/'.$file;
			exit;
		}
	}
}

// /clothing.1 > /clothing/index.html
if (is_file($alt=WEBROOT.REQUEST_PATH.'.1') && is_dir(WEBROOT.REQUEST_PATH)) {
	if (rename($alt, $index)) { // fix if possible
		header('x-msg-app-c: dir created b4 file (renamed)');
	} else {
		header('content-type: text/html; charset=utf-8');
		header('x-msg-app: dir created b4 file (unable to rename)');
		include $alt;
		exit;
	}
}

// handle index.html files generated by wget
// e.g. www.mysite.com/ > www.mysite.com/index.html
if (is_file($f=WEBROOT.REQUEST_PATH.'/index.html')) {
	header('content-type: text/html; charset=utf-8');
	header('x-msg-app: index.html');
	include $f;
	exit;
}

// handle files with querystrings in their names
// e.g. request /assets/main.css?v=2.0.1 (which we have) but nginx failed to deliver due to querystring
// @todo: this is slow, move to nginx conf
if (is_file($f=WEBROOT.$_SERVER['REQUEST_URI'])) {
	if (preg_match('/\.(jpe?g|png|gif|svg|ico|swf|css|js)$/',REQUEST_PATH,$m)) {
		if ($m[1] == 'css') header('content-type: text/css');
		else if ($m[1] == 'js') header('content-type: application/javascript');
		else if ($m[1] == 'swf') header('content-type: application/x-shockwave-flash');
		else header('content-type: image/'.$m[1]);
		header('cache-control: max-age=1800'); // cache handled by nginx
		// rename file so nginx can handle it next time
		$newFile = WEBROOT.REQUEST_PATH;
		if (!is_file($newFile)) {
			rename($f, $newFile);
			if (is_file($newFile))
				$f = $newFile;
		}
	}
	header('x-msg-app: querystring');
	include $f;
	exit;
}

// handle requests with dynamic querystrings
// e.g. request /2014/page.html or /2014/page.html?aid=567 and we only have /2014/page.html?utm_hp_ref=123
// @todo: consider renaming file like above, update script will overwrite with real one if exists
// @todo: consider non-html files
if (!is_dir(WEBROOT.REQUEST_PATH)) {
	$dir = dirname(WEBROOT.REQUEST_PATH);
	if (is_dir($dir)) {
		$files = scandir($dir);
		$reqFileName = basename(REQUEST_PATH);
		foreach ($files as $file) {
			if ($file == '.' || $file == '..') continue;
			if (strpos($file,$reqFileName) === 0) {
				$baseFile = $dir.'/'.$file;
				header('cache-control: max-age=900'); // wait for actual file
				header('x-msg-app: basefile');
				include $baseFile;
				exit;
			}
		}
	}
}


header('x-msg: hit fallback index');
header((isset($_SERVER['SERVER_PROTOCOL'])?$_SERVER['SERVER_PROTOCOL']:'HTTP/1.0').' 404 Not Found');
